version: "3.2"

services:

  ws:
    build:
      context: .
      dockerfile: Dockerfile.ws
    ports:
      - 9120:9120
    container_name: ws
    env_file:
      - .env
    depends_on:
      - nats
      - mongo
    restart: always

  mqtt:
    build:
      context: .
      dockerfile: Dockerfile.mqtt
    container_name: mqtt
    env_file:
      - .env
    depends_on:
      - nats
      - mongo
      - mosquitto
    restart: always

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - "./public:/var/public"
    ports:
      - 80:80
    container_name: nginx
    depends_on:
      - ws
    restart: always

  mongo:
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    env_file:
      - .env
    volumes:
      - "./db/mongo:/data/db"
    restart: always

  nats:
    image: nats
    ports:
      - ${NATS_PORT}:4222
    container_name: nats
    env_file:
      - .env
    command: "--user $NATS_USER --pass $NATS_PASS"
    restart: always

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - ${MQTT_PORT}:1883
    container_name: mosquitto
    env_file:
      - .env
    restart: always